@@include('plans.js')
@@include('reviews_slider.js')
@@include('partners_slider.js')
@@include('faq.js')
@@include('smooth_scroll.js')
@@include('header_burger.js')
@@include('component.js')
@@include('phoneMask.js')
@@include('handler _alert_form.js')